XXXXXXXXX XXXXX

XXXXXX
XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX
        XXXX X
            XXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXX
        X
        XXXX X
            XXXXXXX XXXXX
            XXXXXX XXXXX
        X
        XXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXX XXXX XXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXX XXXXXXXXX XXXXX XXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
        X
        XXXXX X
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
        X
        X X
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
            XXXXXXX XX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXX XX
            XXXXXXX XXXX
            XXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        XXXXXXXX
XXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBXX
        BBBBBBBBBB

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		
        
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        
		
		XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		
        
		XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		
        

        XXXX BB BBBBBBBBBBB
            
        BBBBB XXX

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        
        XX XXXXXXBBB BBBBBBBXXXXXX XXXXXX
    XXXXXXX
XXXXXXX
XXXXXXX