# Generated by Django 3.1.6 on 2021-03-24 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateTimeField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('interval', models.CharField(default='no', max_length=150)),
                ('autoshift', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField()),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, interval='no'), ('autoshift', False)), models.Q(('interval', 'no'), ('autoshift', True)), models.Q(('interval', 'no'), ('autoshift', False)), _connector='OR'), name='interval_or_autoshift'),
        ),
    ]
