# Generated by Django 3.1.6 on 2021-02-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateTimeField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('interval', models.CharField(blank=True, max_length=150)),
                ('autoshift', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('interval__isnull', False), ('autoshift__isnull', True)), models.Q(('interval__isnull', True), ('autoshift__isnull', False)), _connector='OR'), name='only_interval_or_autoshift'),
        ),
        migrations.AddField(
            model_name='file',
            name='related_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task'),
        ),
        migrations.AddField(
            model_name='completion',
            name='related_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task'),
        ),
    ]
