# Generated by Django 3.1.6 on 2021-02-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('initdate', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(max_length=150)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=400)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_when', models.CharField(max_length=20)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
            ],
        ),
        migrations.CreateModel(
            name='Autoshift',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
            ],
        ),
    ]
