# Generated by Django 3.1.6 on 2021-02-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20210212_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoshift',
            old_name='task_id',
            new_name='related_task',
        ),
        migrations.RenameField(
            model_name='completion',
            old_name='task_id',
            new_name='related_task',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='task_id',
            new_name='related_task',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='task_id',
            new_name='related_task',
        ),
    ]
