# Generated by Django 3.1.6 on 2021-02-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20210220_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='autoshift',
            field=models.BooleanField(blank=True),
        ),
    ]
