# Generated by Django 3.1.6 on 2021-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20210212_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshift',
            name='value',
            field=models.CharField(max_length=3),
        ),
    ]
