# Generated by Django 3.1.6 on 2021-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20210220_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.CharField(default='no', max_length=150),
        ),
    ]
