# Generated by Django 3.1.6 on 2021-02-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_auto_20210220_2016'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='only_interval_or_autoshift',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(_negated=True, interval='no'), ('autoshift', False)), models.Q(('interval', 'no'), ('autoshift', True)), models.Q(('interval', 'no'), ('autoshift', False)), _connector='OR'), name='only_interval_or_autoshift'),
        ),
    ]
